import os

from ..helpers import enoent_means_false


PATTERN = '''This documentation was automatically generated by
      <a href="http://codespeak.net/~mwh/pydoctor/">pydoctor</a>'''


@enoent_means_false
def detect(path):
    """Detect whether path is pydoctor documentation."""
    with open(os.path.join(path, 'index.html')) as f:
        return PATTERN in f.read()
