---
version: 2

build:
  os: ubuntu-20.04
  tools:
    # Keep version in sync with docs session in noxfile.py.
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

mkdocs:
  configuration: mkdocs.yml
