---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
