---
site_name: doc2dash
site_author: Hynek Schlawack
copyright: Copyright &copy; 2012 Hynek Schlawack

watch:
  - README.md
  - CHANGELOG.md
  - src/doc2dash/__main__.py
  - src/doc2dash/parsers/types.py

nav:
  - About: index.md
  - Quickstart: quickstart.md
  - Installation: installation.md
  - Supported Formats: formats.md
  - Usage:
    - CLI Reference: cli.md
    - Building & Submitting Docsets: how-to.md
    - Extending: extending.md
  - Meta:
    - License & Credits: credits.md
    - Changelog: https://github.com/hynek/doc2dash/blob/main/CHANGELOG.md
    - Funding: https://hynek.me/say-thanks/

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/hynek/doc2dash
repo_name: hynek/doc2dash
edit_uri: blob/main/docs

extra:
  social:
    - icon: fontawesome/solid/person-circle-question
      link: https://hynek.me/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@hynek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hynek
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hynek
  version:
    provider: mike # liesssss

markdown_extensions:
  - admonition
  - smarty
  - attr_list
  - mkdocs-click
  - pymdownx.smartsymbols
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - callouts
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
