# Pick from https://kapeli.com/docsets#supportedentrytypes

ATTRIBUTE = "Attribute"
CLASS = "Class"
CONSTANT = "Constant"
ENV = "Environment"
EXCEPTION = "Exception"
FUNCTION = "Function"
GUIDE = "Guide"
INTERFACE = "Interface"
MACRO = "Macro"
METHOD = "Method"
OPCODE = "Operator"
OPTION = "Option"
PACKAGE = "Module"
PROPERTY = "Property"
PROTOCOL = "Protocol"
SECTION = "Section"
SETTING = "Setting"
TYPE = "Type"
VALUE = "Value"
VARIABLE = "Variable"
WORD = "Word"
