---
name: Build binaries using pyOxidizer

on:
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_PYTHON_VERSION_WARNING: 1

jobs:
  build:
    name: Build binary for ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install nox
      - run: nox -e oxidize

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/*
