---
name: Build binaries using pyOxidizer

on:
  push:
    tags: ["*"]
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

permissions: {}

jobs:
  build:
    name: Build binary for ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          # Even Go binaries built on 22.04 don't work on 20.04.
          - ubuntu-20.04
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # get correct version
          persist-credentials: false
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          # Double-check latest version supported by PyOxidizer:
          # https://github.com/indygreg/PyOxidizer/releases/
          python-version: "3.10"

      - run: python -Im pip install nox
      - run: nox -e oxidize

      - name: check binary
        shell: bash
        run: |
          cd build/*/release/install/
          ./doc2dash --version
        if: runner.os != 'Windows'

      - name: check windows binary
        shell: bash
        run: |
          cd build/*/release/install/
          ./doc2dash.exe --version
        if: runner.os == 'Windows'

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: binary-${{ matrix.runs-on }}
          path: build/*
